using System.Buffers;
using System.IO.Pipelines;
using System.Security.Cryptography;
using Jakar.OpenTelemetry.Api.Grpc;
using Jakar.OpenTelemetry.Api.Security;
using Jakar.OpenTelemetry.Api.Services;
using Jakar.OpenTelemetry.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Jakar.OpenTelemetry.Api.Endpoints;

/// <summary>
///     Receives screenshots referenced by log records (<c>log.tags</c> = <c>image:{file-name}:{id}</c>).
///     <para>
///         Ids are generated by the clients, so the log can be exported right away and the image uploaded later. Uploads are idempotent (<c>PUT</c>), and the
///         server sheds load with <c>503 + Retry-After</c> instead of buffering, so clients upload "when the server can accept them".
///     </para>
/// </summary>
public sealed class TelemetryImageReceiver : IDisposable
{
	private readonly TelemetryImageStore             _store;
	private readonly OtlpIngestAuthorizer            _authorizer;
	private readonly TelemetryChangeNotifier         _notifier;
	private readonly ILogger<TelemetryImageReceiver> _logger;
	private readonly SemaphoreSlim                   _slots;
	private readonly int                             _maxBytes;
	private readonly string                          _retryAfter;


	public TelemetryImageReceiver( TelemetryImageStore store, OtlpIngestAuthorizer authorizer, TelemetryChangeNotifier notifier, IOptions<OtlpIngestOptions> options, ILogger<TelemetryImageReceiver> logger )
	{
		_store      = store;
		_authorizer = authorizer;
		_notifier   = notifier;
		_logger     = logger;
		_slots      = new SemaphoreSlim( options.Value.MaxConcurrentImageUploads, options.Value.MaxConcurrentImageUploads );
		_maxBytes   = options.Value.MaxImageBytes;
		_retryAfter = options.Value.RetryAfterSeconds.ToString( System.Globalization.CultureInfo.InvariantCulture );
	}

	public void Dispose() => _slots.Dispose();


	public async Task<IResult> PutAsync( Guid id, HttpContext context )
	{
		CancellationToken token   = context.RequestAborted;
		HttpRequest       request = context.Request;

		if ( !_authorizer.IsAuthorized( request.Headers ) ) { return TypedResults.Problem( _authorizer.FailureMessage, statusCode: StatusCodes.Status401Unauthorized ); }

		if ( id == Guid.Empty ) { return TypedResults.Problem( "Image id must not be empty", statusCode: StatusCodes.Status400BadRequest ); }

		string? contentType = NormalizeContentType( request.ContentType );
		if ( contentType is null ) { return TypedResults.Problem( $"Unsupported image Content-Type, expected one of {string.Join( ", ", TelemetryImageStore.AllowedContentTypes )}", statusCode: StatusCodes.Status415UnsupportedMediaType ); }

		if ( request.ContentLength > _maxBytes ) { return TypedResults.Problem( $"Image exceeds {_maxBytes} byte limit", statusCode: StatusCodes.Status413PayloadTooLarge ); }

		// Shed load instead of queueing: the client keeps the image durably and retries after Retry-After.
		if ( !_slots.Wait( 0, token ) ) { return RetryLater( context, "Image uploads at capacity, retry later" ); }

		byte[]? buffer = null;

		try
		{
			( buffer, int length ) = await ReadBodyAsync( request.BodyReader, token );
			if ( length == 0 ) { return TypedResults.Problem( "Image body is empty", statusCode: StatusCodes.Status400BadRequest ); }

			ReadOnlyMemory<byte> data = buffer.AsMemory( 0, length );
			if ( !TelemetryImageStore.MatchesSignature( contentType, data.Span ) ) { return TypedResults.Problem( $"Image body is not a valid {contentType}", statusCode: StatusCodes.Status415UnsupportedMediaType ); }

			byte[] sha256 = SHA256.HashData( data.Span );
			if ( request.Headers.TryGetValue( LogTags.SHA256_HEADER, out Microsoft.Extensions.Primitives.StringValues declared ) &&
				 !MatchesHash( declared.ToString(), sha256 ) ) { return TypedResults.Problem( "Image body does not match the declared SHA-256", statusCode: StatusCodes.Status400BadRequest ); }

			string fileName = ImageTag.SanitizeFileName( Uri.UnescapeDataString( request.Headers[LogTags.FILE_NAME_HEADER].ToString() ) );

			switch ( await _store.SaveAsync( id, fileName, contentType, data, sha256, token ) )
			{
				case ImageSaveResult.Created:
					_notifier.AddImages( 1 );
					return TypedResults.Created( $"{LogTags.IMAGE_ROUTE}/{id:D}" );

				case ImageSaveResult.AlreadyExists:
					return TypedResults.Ok();

				default:
					return TypedResults.Problem( "A different image already exists with this id", statusCode: StatusCodes.Status409Conflict );
			}
		}
		catch ( BadHttpRequestException e ) { return TypedResults.Problem( e.Message.TrimEnd( '.' ),                           statusCode: e.StatusCode ); }
		catch ( InvalidDataException e ) { return TypedResults.Problem( $"Malformed request body: {e.Message.TrimEnd( '.' )}", statusCode: StatusCodes.Status400BadRequest ); }
		catch ( OperationCanceledException ) when ( token.IsCancellationRequested ) { return TypedResults.StatusCode( StatusCodes.Status499ClientClosedRequest ); }
		catch ( Exception e ) when ( OtlpFailure.IsRetryable( e ) )
		{
			_logger.LogWarning( e, "Transient failure storing image {ImageId}, client asked to retry", id );
			return RetryLater( context, OtlpFailure.RETRYABLE_MESSAGE );
		}
		finally
		{
			_slots.Release();
			if ( buffer is not null ) { ArrayPool<byte>.Shared.Return( buffer ); }
		}
	}

	public async Task<IResult> HeadAsync( Guid id, HttpContext context )
	{
		if ( !_authorizer.IsAuthorized( context.Request.Headers ) ) { return TypedResults.StatusCode( StatusCodes.Status401Unauthorized ); }

		return await _store.ExistsAsync( id, context.RequestAborted )
				   ? TypedResults.Ok()
				   : TypedResults.NotFound();
	}

	/// <summary> Serves a stored image to the dashboard. Hardened so the response can only ever be rendered as an inert image. </summary>
	public async Task<IResult> GetAsync( Guid id, HttpContext context )
	{
		if ( await _store.GetAsync( id, context.RequestAborted ) is not { } image ) { return TypedResults.NotFound(); }

		IHeaderDictionary headers = context.Response.Headers;
		headers.CacheControl          = "private, max-age=31536000, immutable"; // ids are immutable
		headers.XContentTypeOptions   = "nosniff";
		headers.ContentSecurityPolicy = "default-src 'none'; sandbox";
		return TypedResults.File( image.Data, image.ContentType );
	}


	private IResult RetryLater( HttpContext context, string message )
	{
		context.Response.Headers.RetryAfter = _retryAfter;
		return TypedResults.Problem( message, statusCode: StatusCodes.Status503ServiceUnavailable );
	}

	/// <summary> Reads the (possibly decompressed, possibly chunked) body into one pooled buffer, enforcing the size limit while reading. </summary>
	private async Task<(byte[] Buffer, int Length)> ReadBodyAsync( PipeReader reader, CancellationToken token )
	{
		while ( true )
		{
			ReadResult             result = await reader.ReadAsync( token );
			ReadOnlySequence<byte> body   = result.Buffer;

			if ( body.Length > _maxBytes )
			{
				reader.AdvanceTo( body.End );
				throw new BadHttpRequestException( $"Image exceeds {_maxBytes} byte limit", StatusCodes.Status413PayloadTooLarge );
			}

			if ( !result.IsCompleted )
			{
				reader.AdvanceTo( body.Start, body.End );
				continue;
			}

			int    length = (int)body.Length;
			byte[] buffer = ArrayPool<byte>.Shared.Rent( Math.Max( length, 1 ) );
			body.CopyTo( buffer );
			reader.AdvanceTo( body.End );
			return ( buffer, length );
		}
	}

	private static string? NormalizeContentType( string? contentType )
	{
		if ( string.IsNullOrEmpty( contentType ) ) { return null; }

		ReadOnlySpan<char> mediaType = contentType.AsSpan();
		int                separator = mediaType.IndexOf( ';' );
		if ( separator >= 0 ) { mediaType = mediaType[..separator]; }

		mediaType = mediaType.Trim();

		foreach ( string allowed in TelemetryImageStore.AllowedContentTypes )
		{
			if ( mediaType.Equals( allowed, StringComparison.OrdinalIgnoreCase ) ) { return allowed; }
		}

		return mediaType.Equals( "image/jpg", StringComparison.OrdinalIgnoreCase )
				   ? "image/jpeg"
				   : null;
	}

	private static bool MatchesHash( string declared, byte[] actual )
	{
		Span<byte> expected = stackalloc byte[32];
		return Convert.TryFromBase64String( declared.Trim(), expected, out int written ) && written == 32 && CryptographicOperations.FixedTimeEquals( expected, actual );
	}
}

public static class ImageEndpointMappings
{
	public const string DASHBOARD_IMAGE_ROUTE = "/telemetry/images";

	public static string DashboardImageUrl( Guid id ) => $"{DASHBOARD_IMAGE_ROUTE}/{id:D}";

	public static WebApplication MapImageEndpoints( this WebApplication app, int maxImageBytes )
	{
		RouteGroupBuilder ingest = app.MapGroup( LogTags.IMAGE_ROUTE ).AllowAnonymous().DisableAntiforgery().WithTags( "Images" ).WithMetadata( new RequestSizeLimitAttribute( maxImageBytes ) );

		ingest.MapPut( "/{id:guid}", static ( Guid id, HttpContext context, TelemetryImageReceiver receiver ) => receiver.PutAsync( id, context ) ).WithName( "UploadImage" ).WithSummary( "Upload an image referenced by a log record" ).WithDescription( "Idempotent upload of an image whose client-generated id is referenced from a log's `log.tags` attribute as `image:{file-name}:{id}`. Requires the OTLP API key header. Returns 503 + Retry-After when the server is at capacity" );

		ingest.MapMethods( "/{id:guid}", [ HttpMethods.Head ], static ( Guid id, HttpContext context, TelemetryImageReceiver receiver ) => receiver.HeadAsync( id, context ) ).WithName( "ImageExists" ).WithSummary( "Check whether an image has been uploaded" );

		app.MapGet( $"{DASHBOARD_IMAGE_ROUTE}/{{id:guid}}", static ( Guid id, HttpContext context, TelemetryImageReceiver receiver ) => receiver.GetAsync( id, context ) ).RequireAuthorization( AppAuthPolicies.DASHBOARD_ACCESS ).ExcludeFromDescription();

		return app;
	}
}
